## 1. Introduction

NumPy (Numerical Python) is one of the most important libraries in Python for scientific computing, data analysis, and AI/ML. It provides a powerful array-based data structure called the NumPy array, which is essential for handling and performing fast mathematical operations on large datasets.

What is an Array?
An array is a data structure that stores a collection of items, usually numbers, where each item is accessed by its position (or index) in the sequence. Unlike lists in Python, arrays require all elements to be of the same data type (such as all integers or all floats).

In [3]:
#import library
import numpy as np

In [4]:
np

<module 'numpy' from 'E:\\python\\Lib\\site-packages\\numpy\\__init__.py'>

In [8]:
lst=[1,2,3,4]
arr=np.array(lst)

In [10]:
type(arr)
arr.shape

(4,)

In [11]:
lst1=[1,2,3]
lst2=[4,5,6]
lst3=[7,8,9]



In [13]:
arr1=np.array([lst1,lst2,lst3])

In [15]:
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr1.shape

(3, 3)

In [20]:
arr1[:,1]

array([2, 5, 8])

In [21]:
arr1[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr1[:,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [36]:
np.arange(1,11,1).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
np.arange(1,11,1).reshape(2,5,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [42]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [43]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [68]:
np.random.randint(1,23,5)

array([10, 16,  9, 20,  6], dtype=int32)